Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
  
    config.vm.define "server" do |server|
      server.vm.hostname = "jucapikS"
      server.vm.network "private_network", ip: "192.168.56.110"
  
      server.vm.provider "virtualbox" do |vb|
        vb.name = "jucapikS"
        vb.cpus = 2
        vb.memory = 2048
      end
  
      server.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
        echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
        apt-get update
        apt-get install -y docker-ce
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=none --apiserver-ips=192.168.56.110
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
      SHELL
  
      server.vm.provision "shell", inline: <<-SHELL
        kubectl create namespace my-apps
        kubectl apply -f /vagrant/app1/deployment.yaml -n my-apps
        kubectl apply -f /vagrant/app1/service.yaml -n my-apps
        kubectl apply -f /vagrant/app2/deployment.yaml -n my-apps
        kubectl apply -f /vagrant/app2/service.yaml -n my-apps
        kubectl apply -f /vagrant/app3/deployment.yaml -n my-apps
        kubectl apply -f /vagrant/app3/service.yaml -n my-apps
        kubectl apply -f /vagrant/ingress/ingress.yaml -n my-apps
      SHELL
    end
  end
  