Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"

    config.ssh.insert_key = false
    unless File.exist?("keys/id_rsa")
      system('mkdir -p keys && ssh-keygen -t rsa -N "" -f keys/id_rsa')
    end
    config.vm.provision "file", source: "keys/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  
    # Machine Serveur
    config.vm.define "server" do |server|
      server.vm.hostname = "loginS"
      server.vm.network "private_network", ip: "192.168.56.110"
  
      server.vm.provider "virtualbox" do |vb|
        vb.name = "loginS"
        vb.cpus = 1
        vb.memory = 1024
      end
  
      server.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y curl
        curl -sfL https://get.k3s.io | sh -

        mkdir -p /vagrant/shared
        cp /var/lib/rancher/k3s/server/node-token /vagrant/shared/node-token
        apt-get install -y kubectl

        mkdir -p /home/vagrant/.ssh
        cat /vagrant/keys/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
        chown -R vagrant:vagrant /home/vagrant/.ssh
        chmod 600 /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  
    # Machine Worker
    config.vm.define "worker" do |worker|
      worker.vm.hostname = "loginSW"
      worker.vm.network "private_network", ip: "192.168.56.111"
  
      worker.vm.provider "virtualbox" do |vb|
        vb.name = "loginSW"
        vb.cpus = 1
        vb.memory = 1024
      end
  
      worker.vm.provision "shell", inline: <<-SHELL
        while [ ! -f /vagrant/shared/node-token ]; do
          sleep 2
        done
        NODE_TOKEN=$(cat /vagrant/shared/node-token)
  
        apt-get update
        apt-get install -y curl
        K3S_URL="https://192.168.56.110:6443" K3S_TOKEN=$NODE_TOKEN sh -c 'curl -sfL https://get.k3s.io | sh -'
        apt-get install -y kubectl
  
        mkdir -p /home/vagrant/.ssh
        cat /vagrant/keys/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
        chown -R vagrant:vagrant /home/vagrant/.ssh
        chmod 600 /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end
  