Vagrant.configure("2") do |config|

  config.vm.define "naaliS" do |naaliS|
    naaliS.vm.box = "debian/bookworm64"
    naaliS.vm.hostname = "naaliS"
    
    naaliS.vm.network "private_network", ip: "192.168.56.110"

    naaliS.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    naaliS.vm.provision "shell", path: "./scripts/setup_server.sh"
  end

  config.vm.define "naaliSW" do |naaliSW|
    naaliSW.vm.box = "debian/bookworm64"
    naaliSW.vm.hostname = "naaliSW"

    naaliSW.vm.network "private_network", ip: "192.168.56.111"

    naaliSW.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    naaliSW.vm.provision "shell", path: "./scripts/setup_worker.sh"
  end

end
